Python 3.14.3 (tags/v3.14.3:323c59a, Feb  3 2026, 16:04:56) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> import cv2
... import time
... from djitellopy import Tello
... 
... tello = Tello()
... tello.connect()
... 
... tello.streamon()
... frame_read = tello.get_frame_read()
... 
... x = int(input("How many times do you want the drone to fly?"))
... y = int(input("How many photos do you want the drone to take?"))
... z = int(input("How long do you want the drone to pause between taking photos?"))
... e=  int(input("How far away is the target in cm?"))
... 
... for flight in range(1, x + 1):
... 
...     tello.takeoff()
...     tello.move_forward(e)
... 
...     for pic in range(1, y + 1):
... 
...         frame = frame_read.frame
...         cv2.imwrite(f"flight{flight}_pic{pic}.png", frame)
... 
...         time.sleep(z)
... 
... 
...     tello.move_back(e)
...     tello.land()
... 
... 
